// resources/js/pages/projects/Index.tsx
import { Heading } from "@/components/catalyst/heading";
import { DashboardLayout } from "@/layouts/DashboardLayout";
import type { PaginatedModel, Project } from "@/lib/models";
import { NoProjectsPlaceholder } from "@/pages/projects/partials/NoProjectsPlaceholder";
import type { PageProps } from "@/types";
import { Head } from "@inertiajs/react";

export default function Index({
    auth,
    projects,
}: PageProps<{ projects: PaginatedModel<Project> }>) {
    return (
        <DashboardLayout user={auth.user}>
            <Head title="Projects" />
            <Heading>Projects</Heading>
            {projects.data.length !== 0 && <NoProjectsPlaceholder />}
        </DashboardLayout>
    );
}

// resources/js/pages/projects/Index.vue
<script lang="ts" setup>
import { Head } from '@inertiajs/vue3';
import ProjectSummaryCard from './partials/ProjectSummaryCard.vue';
import AuthenticatedLayout from '@/layouts/AuthenticatedLayout.vue';
import type { PaginatedModel, Project } from '@/lib/models';

defineProps<{
    projects: PaginatedModel<Project>;
}>();
</script>

<template>
    <AuthenticatedLayout header-text="Projects">
        <Head title="Projects" />
        <div class="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
            <ProjectSummaryCard v-for="project in projects.data" :key="project.id" :project="project" />
        </div>
    </AuthenticatedLayout>
</template>
