// resources/js/pages/profile/Edit.tsx
import { DashboardLayout } from "@/layouts/DashboardLayout";
import type { PageProps } from "@/types";
import { Head } from "@inertiajs/react";
import DeleteUserForm from "./partials/DeleteUserForm";
import UpdatePasswordForm from "./partials/UpdatePasswordForm";
import UpdateProfileInformationForm from "./partials/UpdateProfileInformationForm";

export default function Edit({
    auth,
    mustVerifyEmail,
    status,
}: PageProps<{ mustVerifyEmail: boolean; status?: string }>) {
    return (
        <DashboardLayout user={auth.user}>
            <Head title="Profile" />

            <div className="py-12">
                <div className="mx-auto max-w-7xl space-y-6 lg:px-8 sm:px-6">
                    <div className="p-4 shadow sm:rounded-lg sm:p-8">
                        <UpdateProfileInformationForm
                            mustVerifyEmail={mustVerifyEmail}
                            status={status}
                            className="max-w-xl"
                        />
                    </div>

                    <div className="p-4 shadow sm:rounded-lg sm:p-8">
                        <UpdatePasswordForm className="max-w-xl" />
                    </div>

                    <div className="p-4 shadow sm:rounded-lg sm:p-8">
                        <DeleteUserForm className="max-w-xl" />
                    </div>
                </div>
            </div>
        </DashboardLayout>
    );
}

// resources/js/pages/profile/Edit.vue
<script lang="ts" setup>
import { Head } from '@inertiajs/vue3';
import UpdatePasswordForm from './partials/UpdatePasswordForm.vue';
import AuthenticatedLayoutV2 from '@/layouts/AuthenticatedLayoutV2.vue';
import UpdateProfileInformationForm from '@/pages/profile/partials/UpdateProfileInformationForm.vue';
import DeleteUserForm from '@/pages/profile/partials/DeleteUserForm.vue';

defineProps<{
    mustVerifyEmail?: boolean;
    status?: string;
}>();
</script>

<template>
    <Head title="Profile" />

    <AuthenticatedLayoutV2 header-text="My account">
        <form>
            <div class="space-y-12">
                <UpdateProfileInformationForm :must-verify-email="mustVerifyEmail" :status="status" />
                <UpdatePasswordForm />
                <DeleteUserForm />
            </div>
        </form>
    </AuthenticatedLayoutV2>
</template>
